# تنظیمات سرور
server.port=8080

# تنظیمات دیتابیس (اختیاری اگر بخوای Spring Boot مستقیم وصل بشه)
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=${PG_PASS}

# تلگرام
telegram.bot.token=${BOT_TOKEN}
telegram.chat.id=${CHAT_ID}
